Repository ctc-oss/fapolicy-analyzer, pull requests merged in 2021-09, with the labels that each got.

#210 chore: fixed double quote lint warning
  python/.flake8
  python/Pipfile
  python/Pipfile.lock
Labels: ui

#223 fixup: Actual metadata
  crates/analyzer/src/check.rs
  crates/analyzer/src/error.rs
  crates/analyzer/src/trust.rs
  crates/pyo3/src/trust.rs
  examples/show_trust.py
Labels: bindings

#248 Update documentation to match recent refactoring efforts (#245)
  README.md
Labels: documentation

#251 fix: misspelling Anaylze -> Analyze in UI (#250)
  fapolicy_analyzer/glade/main_window.glade
  fapolicy_analyzer/locale/fapolicy_analyzer.pot
Labels: frontend

#263 vagrant & Ansible configured with git branch to checkout & build (#262)
  scripts/demo/develop/tasks/main.yml
  scripts/demo/group_vars/all.yml
  scripts/vagrant/fc34/Vagrantfile
  scripts/vagrant/rhel8/Vagrantfile
Labels: enhancement

#256 fix: remove duplicate Close button in About window (#255)
  fapolicy_analyzer/glade/main_window.glade
Labels: bug, frontend
